# vi: ft=bash

# Utility
alias reload='source ~/.zshrc'

# default params
alias less='less -R'

cdc() {
    cd $1; ls
}

take() {
    mkdir -p "$1"
    cd "$1"
}

alias e='exit'
alias k9="killall -9"

killnamed() {
    ps ax | grep $1 | cut -d ' ' -f 2 | xargs kill
}

nuke() {
  pkill -9 -f $1
}

zipr() {
  zip -r $1.zip $1
}

alias md='mkdir -p'
alias rm='rm -i'
alias mv='mv -i'

alias h='history'
alias j='jobs -l'
alias which='type -a'
alias ..='cd ..'
alias cl='clear; l'
alias cls='clear; ls'

alias untar='tar -zxvf'

alias path='echo -e ${PATH//:/\\n}' # easier to read

alias du='du -kh'    # Makes a more readable output.
alias df='df -kTh'


alias ls='exa'              # use EXA instead of ls

alias l.='ls -d .[^.]*'     # List hidden directories only
alias l='ls -lhG -snew'     # -l long listing, most recent first -G color
alias lc='ls -ltcr'         # Sort by/show change time,most recent last.
alias lh="ls -alh"          # most recent first
alias lk='ls -lssize'       # Sort by size, biggest last.
alias ll='ls -alhg --git'   # show git status (exa feature)
alias lm='ll | less'        # Pipe through 'less'
alias lr='ll -R'            # Recursive ls.
alias lt='ls -lt'           # sort with recently modified first
alias lt='ls -ltr'          # Sort by date, most recent last.
alias lu='ls -ltur'         # Sort by/show access time,most recent last.
alias lx='ls -lXB'          # Sort by extension.

# find a file inside this directory tree
ff() {
  find . -type f -iname '*'"$*"'*' -ls ;
}

# find a file in the entire filesystem
ffr() {
  find / -type f -iname '*'"$*"'*' -ls ;
}

# find a file inside the $HOME tree
ffh() {
  find ${HOME} -type f -iname '*'"$*"'*' -ls ;
}

# find file containing the supplied text, inside this directory tree
fif() {
  find . -type f -exec grep -l "${1}" "{}" \;
}

# find file containing the supplied text, in the entire filesystem
fifa() {
  find / -type f -exec grep -l "${1}" "{}" \;
}

# find file containing the supplied text, inside the $HOME tree
fifd() {
  find ${HOME} -type f -exec grep -l "${1}" "{}" \;
}

# find file containing the supplied text, inside this directory tree and print its contents
fifp() {
  find . -type f -exec grep -i "${1}" "{}" \; -print
}

# find file containing the supplied text, in the entire filesystem and print its contents
fifap() {
  find / -type f -exec grep -i "${1}" "{}" \; -print
}

# find file containing the supplied text, inside the $HOME tree and print its contents
fifdp() {
  find ${HOME} -type f -exec grep -l "${1}" "{}" \; -print
}

# du, sorted by size and human-readable
duf() {
  du -s $* | sort -n | cut -f 2- | while read a; do du -sh $a; done
}

# lazygit rocks
alias lg='lazygit'

alias sshm='ssh maschine -X'
alias sshk='kitty +kitten ssh'

# mount the home directory of the development machine in this filesystem
mount_maschine() {
  sshfs -o IdentityFile=/home/miguel/.ssh/id_rsa miguel@maschine:/home/miguel ~/maschine/
}

alias whatsmyip="curl https://api.myip.com"

unalias gdu 2>/dev/null
alias freespace="/bin/gdu"
