# vi: ft=bash

# load the creds
# source ~/.pn_anonymize_creds

# for Rails projects
rall () {
  tmux split-window -vp 20
  tmux split-window -hp 45
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'nvim' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux send-keys -t 3 'nix-shell' Enter

  tmux new-window

  tmux split-window -hp 50
  tmux split-window -vp 80
  tmux split-window -vp 70
  tmux select-pane -t 1
  tmux split-window -vp 15
  tmux send-keys -t 3 'nix-shell' Enter
  tmux send-keys -t 3 'docker-compose up' Enter
  tmux send-keys -t 4 'nix-shell' Enter
  # tmux send-keys -t 4 'bundle exec sidekiq start' Enter
  tmux send-keys -t 5 'nix-shell' Enter
  tmux send-keys -t 5 'bundle exec rails server -b 0.0.0.0 -p 3000' Enter
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'lazygit' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux select-pane -t 1

  tmux select-window -t !
}

redit () {
  tmux split-window -vp 20
  tmux split-window -hp 45
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'nvim' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux send-keys -t 3 'nix-shell' Enter
}

rsupport() {
  tmux split-window -hp 50
  tmux split-window -vp 80
  tmux split-window -vp 70
  tmux select-pane -t 1
  tmux split-window -vp 15
  tmux send-keys -t 3 'nix-shell' Enter
  tmux send-keys -t 3 'docker-compose up' Enter
  tmux send-keys -t 4 'nix-shell' Enter
  # tmux send-keys -t 4 'bundle exec sidekiq start' Enter
  tmux send-keys -t 5 'nix-shell' Enter
  tmux send-keys -t 5 'bundle exec rails server -b 0.0.0.0 -p 3000' Enter
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'lazygit' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux select-pane -t 1
}

# for Ember projects
eall () {
  tmux split-window -vp 20
  tmux split-window -hp 45
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'nvim' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux send-keys -t 3 'nix-shell' Enter

  tmux new-window

  tmux split-window -hp 50
  tmux split-window -vp 80
  tmux split-window -vp 70
  tmux select-pane -t 1
  tmux split-window -vp 15
  tmux send-keys -t 3 'nix-shell' Enter
  tmux send-keys -t 3 'yarn start' Enter
  tmux send-keys -t 4 'nix-shell' Enter
  tmux send-keys -t 5 'nix-shell' Enter
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'lazygit' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux select-pane -t 1

  tmux select-window -t !
}

eedit () {
  tmux split-window -vp 20
  tmux split-window -hp 45
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'nvim' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux send-keys -t 3 'nix-shell' Enter
}

esupport() {
  tmux split-window -hp 50
  tmux split-window -vp 80
  tmux split-window -vp 70
  tmux select-pane -t 1
  tmux split-window -vp 15
  tmux send-keys -t 3 'nix-shell' Enter
  tmux send-keys -t 3 'yarn start' Enter
  tmux send-keys -t 4 'nix-shell' Enter
  tmux send-keys -t 5 'nix-shell' Enter
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'lazygit' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux select-pane -t 1
}

alias rsh='nix-shell'
alias esh='nix-shell'
alias rdbm='rails db:migrate && rails erd'
alias be='bundle exec'
