# vi: ft=bash

# load the creds
# source ~/.pn_anonymize_creds

# for Rails projects
rall () {
  tmux rename-window 'rb edit'
  tmux split-window -vp 15
  tmux split-window -hp 45
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'nvim' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux send-keys -t 3 'nix-shell' Enter

  tmux new-window

  tmux rename-window 'rb support'
  tmux split-window -hp 50
  tmux split-window -vp 80
  tmux split-window -vp 70
  tmux select-pane -t 1
  tmux split-window -vp 15
  tmux send-keys -t 3 'nix-shell' Enter
  tmux send-keys -t 3 'docker-compose up' Enter
  tmux send-keys -t 4 'nix-shell' Enter
  tmux send-keys -t 4 'rails tailwindcss:watch' Enter
  tmux send-keys -t 5 'nix-shell' Enter
  tmux send-keys -t 5 'rails server -b 0.0.0.0 -p 3999' Enter
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'lazygit' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux select-pane -t 1

  tmux select-window -t !
}

redit () {
  tmux rename-window 'rb edit'
  tmux split-window -vp 15
  tmux split-window -hp 45
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'nvim' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux send-keys -t 3 'nix-shell' Enter
}

rsupport() {
  tmux rename-window 'rb support'
  tmux split-window -hp 50
  tmux split-window -vp 80
  tmux split-window -vp 70
  tmux select-pane -t 1
  tmux split-window -vp 15
  tmux send-keys -t 3 'nix-shell' Enter
  tmux send-keys -t 3 'docker-compose up' Enter
  tmux send-keys -t 4 'nix-shell' Enter
  tmux send-keys -t 4 'rails tailwindcss:watch' Enter
  tmux send-keys -t 5 'nix-shell' Enter
  tmux send-keys -t 5 'rails server -b 0.0.0.0 -p 3999' Enter
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'lazygit' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux select-pane -t 1
}

# for Ember projects
eall () {
  tmux rename-window 'ember edit'
  tmux split-window -vp 15
  tmux split-window -hp 45
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'nvim' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux send-keys -t 3 'nix-shell' Enter
  tmux send-keys -t 3 'yarn start' Enter

  tmux new-window

  tmux rename-window 'ember support'
  tmux split-window -hp 50
  tmux split-window -vp 80
  tmux split-window -vp 70
  tmux select-pane -t 1
  tmux split-window -vp 15
  tmux send-keys -t 3 'nix-shell' Enter
  tmux send-keys -t 4 'nix-shell' Enter
  tmux send-keys -t 5 'nix-shell' Enter
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'lazygit' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux select-pane -t 1

  tmux select-window -t !
}

eedit () {
  tmux rename-window 'ember edit'
  tmux split-window -vp 15
  tmux split-window -hp 45
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'nvim' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux send-keys -t 3 'nix-shell' Enter
  tmux send-keys -t 3 'yarn start' Enter
}

esupport() {
  tmux rename-window 'ember support'
  tmux split-window -hp 50
  tmux split-window -vp 80
  tmux split-window -vp 70
  tmux select-pane -t 1
  tmux split-window -vp 15
  tmux send-keys -t 3 'nix-shell' Enter
  tmux send-keys -t 4 'nix-shell' Enter
  tmux send-keys -t 5 'nix-shell' Enter
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'lazygit' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux select-pane -t 1
}

create_repo() {
  gh repo create "$@"
  glab repo create "$@"
  git remote add hub git@github.com:miguelverissimo/"$@".git
  git remote add lab git@github.com:miguelverissimo/"$@".git
  git remote set-url --push all git@github.com:miguelverissimo/"$@".git
  git remote set-url --push all git@gitlab.com:miguelverissimo/"$@".git
}

alias ns='nix-shell'
alias rsh='nix-shell'
alias esh='nix-shell'
alias rdbm='rails db:migrate'
alias dbmig='rails db:migrate && rails erd'
alias be='bundle exec'
alias dcu='docker-compose up'
alias dcud='docker-compose up -d'
alias dcd='docker-compose down'
