# vi: ft=bash

ss() {
  tmux new-window -n log
  tmux split-window -vp 90
  tmux split-window -vp 30
  tmux send-keys -t 1 'docker-compose up' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux send-keys -t 2 'bundle exec rails server' Enter
  tmux send-keys -t 3 'nix-shell' Enter
  tmux send-keys -t 3 'bundle exec rails console' Enter
  tmux last-window
  tmux send-keys 'nix-shell' Enter
  tmux send-keys 'nvim' Enter
}
