# vi: ft=bash

# load the creds
source ~/.pn_anonymize_creds

# Story because too lazy to copy/paste
story() {
  if [[ "${1}" == "master" ]]; then
    echo -n >| ~/.gitmessage
    echo "Cleared out story number"
  elif [[ "${1}" == "--query" || "${1}" == "-?" || "${1}" == "-q" ]]; then
    cat ~/.gitmessage | tail -1
  elif [[ "${1}" == "--clear" || "${1}" == "-C" || "${1}" == "-c" ]]; then
    echo -n >| ~/.gitmessage
    echo "Cleared out story number"
  elif [[ "${1}" =~ ^[A-Z0-9]+-[0-9]+$ ]]; then
    echo -e "[${1}]\n\n[${1}](https://precisionnutrition.atlassian.net/browse/${1})" >| ~/.gitmessage
    echo "Set story to ${1}"
  elif [[ "${1}" =~ ^https://.*$ ]]; then
    story_id=$(echo -n ${1} | cut -d'/' -f5)
    echo -e "[${story_id}]\n\n[${story_id}](https://precisionnutrition.atlassian.net/browse/${story_id})" >| ~/.gitmessage
    echo "Set story to ${story_id}"
  else
    current_story=$(cat ~/.gitmessage | tail -1)
    if [ -s ~/.gitmessage ]; then echo "Current story: ${current_story}\n"; fi
    echo "usage: story [-h] [--clear|-c|-C] [--query|-q|-?] [story id]"
    echo -e "\t--query, -q, -?\t  shows tracked story"
    echo -e "\t--clear, -c, -C\t  unsets tracked story"
    echo -e "\t--help, -h\t  help (this)"
    echo -e "\t[story id]\t  sets tracked story to [story id]"
  fi
}

pnsw() {
  ticket="${1}"
  git switch "${ticket}"
  story "${ticket}"
}

pnswc() {
  ticket="${1}"
  git switch -c "${ticket}"
  story "${ticket}"
}

pnall() {
  # pnedit
  cd /home/miguel/DEV/PN/eternal-sledgehammer
  tmux rename-window 'es edit'
  tmux split-window -vp 20 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux split-window -hp 45 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux send-keys -t 1 'pndev shell' Enter
  tmux send-keys -t 1 'nvim' Enter
  tmux send-keys -t 2 'pndev shell' Enter
  tmux send-keys -t 3 'pndev shell' Enter

  tmux new-window -c '/home/miguel/DEV/PN/eternal-sledgehammer'

  # pnsupport
  tmux rename-window 'es support'
  tmux split-window -hp 50 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux split-window -vp 80 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux split-window -vp 70 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux select-pane -t 1
  tmux split-window -vp 15 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux send-keys -t 3 'pndev shell' Enter
  tmux send-keys -t 3 'forego start webpacker -e .env' Enter
  tmux send-keys -t 4 'pndev shell' Enter
  tmux send-keys -t 4 'DEBUG_RULES=true forego start job -e .env' Enter
  tmux send-keys -t 5 'pndev shell' Enter
  tmux send-keys -t 5 'bundle exec rails server -b 0.0.0.0 -p 3000' Enter
  tmux send-keys -t 1 'cd /home/miguel/DEV/PN/eternal-sledgehammer' Enter
  tmux send-keys -t 1 'pndev shell' Enter
  tmux send-keys -t 1 'lg' Enter
  tmux send-keys -t 2 'pndev shell' Enter
  tmux select-pane -t 1

  tmux select-window -t !
}

pnedit() {
  cd /home/miguel/DEV/PN/eternal-sledgehammer
  tmux rename-window 'es edit'
  tmux split-window -vp 20 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux split-window -hp 45 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux send-keys -t 1 'pndev shell' Enter
  tmux send-keys -t 1 'nvim' Enter
  tmux send-keys -t 2 'pndev shell' Enter
  tmux send-keys -t 3 'pndev shell' Enter
}

pnsupport() {
  tmux rename-window 'es support'
  tmux split-window -hp 50 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux split-window -vp 80 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux split-window -vp 70 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux select-pane -t 1
  tmux split-window -vp 15 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux send-keys -t 3 'pndev shell' Enter
  tmux send-keys -t 3 'forego start webpacker -e .env' Enter
  tmux send-keys -t 4 'pndev shell' Enter
  tmux send-keys -t 4 'DEBUG_RULES=true forego start job -e .env' Enter
  tmux send-keys -t 5 'pndev shell' Enter
  tmux send-keys -t 5 'bundle exec rails server -b 0.0.0.0 -p 3000' Enter
  tmux send-keys -t 1 'cd /home/miguel/DEV/PN/eternal-sledgehammer' Enter
  tmux send-keys -t 1 'pndev shell' Enter
  tmux send-keys -t 1 'lg' Enter
  tmux send-keys -t 2 'pndev shell' Enter
  tmux select-pane -t 1
}

pndebug() {
  tmux split-window -vp 80 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux split-window -vp 70 -c '/home/miguel/DEV/PN/eternal-sledgehammer'
  tmux send-keys -t 1 'cd /home/miguel/DEV/PN/eternal-sledgehammer' Enter
  tmux send-keys -t 1 'pndev shell' Enter
  tmux send-keys -t 1 'bundle exec bin/webpack-dev-server' Enter
  tmux send-keys -t 2 'pndev shell' Enter
  tmux send-keys -t 2 'bundle exec sidekiq start' Enter
  tmux send-keys -t 3 'pndev shell' Enter
  tmux send-keys -t 3 'bundle exec rails server -b 0.0.0.0 -p 3000' Enter
}

alias pe=pnedit
alias pd=pndebug
alias psh='pndev shell'
alias pst='cd ~/DEV/PN/eternal-sledgehammer && pndev start'
