# vi: ft=bash

# load the creds
# source ~/.pn_anonymize_creds

# Story because too lazy to copy/paste
rdebug() {
  tmux split-window -vp 80
  tmux split-window -vp 80
  tmux send-keys -t 1 'nix-shell' Enter
  tmux send-keys -t 1 'bundle exec sidekiq start' Enter
  tmux send-keys -t 2 'nix-shell' Enter
  tmux send-keys -t 2 'bundle exec bin/webpack-dev-server' Enter
  tmux send-keys -t 3 'nix-shell' Enter
  tmux send-keys -t 3 'bundle exec rails server -b 0.0.0.0 -p 3000' Enter
}

alias rd=rdebug
alias rsh='nix-shell'
alias rdbm='rails db:migrate && rails erd'
