git:
    commitPrefixes:
      eternal-sledgehammer: # This is repository folder name
        pattern: "^\\w+\\/(\\w+-\\w+).*"
        replace: "[$1] "

gui:
    showFileTree: true

theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue # set to `default` to have no background colour
    selectedRangeBgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
