#!/usr/bin/env bash

# tmux new-session -s 'pivnet' -n 'running' -d

tmux split-window -vp 80
tmux split-window -vp 80
tmux split-window -vp 80
tmux send-keys -t 1 'cd ~/DEV/PN/eternal-sledgehammer' Enter
tmux send-keys -t 1 'pndev shell' Enter
tmux send-keys -t 1 'bundle exec sidekiq start' Enter
tmux send-keys -t 2 'cd ~/DEV/PN/eternal-sledgehammer' Enter
tmux send-keys -t 2 'pndev shell' Enter
tmux send-keys -t 2 'bundle exec bin/webpack-dev-server' Enter
tmux send-keys -t 3 'cd ~/DEV/PN/eternal-sledgehammer' Enter
tmux send-keys -t 3 'pndev shell' Enter
tmux send-keys -t 3 'bundle exec rails server -b 0.0.0.0 -p 3000' Enter
