# vi: ft=bash
export ENCORE_INSTALL="/home/miguel/.encore"

# PATH STUFF
export PATH="$HOME/.local/nvim/bin:$PATH"
export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH"
export PATH="$PATH:$ENCORE_INSTALL/bin"
export PATH="$PATH:$HOME/.bun/bin"
export PATH="$PATH:$HOME/.dotfiles/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.yarn/bin"
export PATH="$PATH:$HOME/.dotfiles/bin/diff-so-fancy"
export PATH="$PATH:$HOME/Applications"
