# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# added by Nix installer
if [ -e /home/miguel/.nix-profile/etc/profile.d/nix.sh ]; then
  source /home/miguel/.nix-profile/etc/profile.d/nix.sh;
fi
